import { Exercise } from "./types";

export const backExercises: Exercise[] = [
  {
    id: "wide-grip-pull-up",
    name: "Wide Grip Pull-Up",
    muscle: "back",
    category: "compound",
    equipment: "bodyweight",
  },
  {
    id: "close-grip-pull-up",
    name: "Close Grip Pull-Up",
    muscle: "back",
    category: "compound",
    equipment: "bodyweight",
  },
  {
    id: "neutral-grip-pull-up",
    name: "Neutral Grip Pull-Up",
    muscle: "back",
    category: "compound",
    equipment: "bodyweight",
  },
  {
    id: "conventional-deadlift",
    name: "Conventional Deadlift",
    muscle: "back",
    category: "compound",
    equipment: "barbell",
  },
  {
    id: "romanian-deadlift",
    name: "Romanian Deadlift",
    muscle: "back",
    category: "compound",
    equipment: "barbell",
  },
  {
    id: "barbell-bent-over-row",
    name: "Barbell Bent Over Row",
    muscle: "back",
    category: "compound",
    equipment: "barbell",
  },
  {
    id: "underhand-barbell-row",
    name: "Underhand Barbell Row",
    muscle: "back",
    category: "compound",
    equipment: "barbell",
  },
  {
    id: "t-bar-row",
    name: "T-Bar Row",
    muscle: "back",
    category: "compound",
    equipment: "barbell",
  },
  {
    id: "landmine-row",
    name: "Landmine Row",
    muscle: "back",
    category: "compound",
    equipment: "landmine",
  },
  {
    id: "one-arm-dumbbell-row",
    name: "One Arm Dumbbell Row",
    muscle: "back",
    category: "compound",
    equipment: "dumbbell",
  },
  {
    id: "chest-supported-dumbbell-row",
    name: "Chest Supported Dumbbell Row",
    muscle: "back",
    category: "compound",
    equipment: "dumbbell",
  },
  {
    id: "dumbbell-deadlift",
    name: "Dumbbell Deadlift",
    muscle: "back",
    category: "compound",
    equipment: "dumbbell",
  },
  {
    id: "dumbbell-pullover",
    name: "Dumbbell Pullover",
    muscle: "back",
    category: "isolation",
    equipment: "dumbbell",
  },
  {
    id: "seated-cable-row",
    name: "Seated Cable Row",
    muscle: "back",
    category: "compound",
    equipment: "cable",
  },
  {
    id: "wide-grip-cable-row",
    name: "Wide Grip Cable Row",
    muscle: "back",
    category: "compound",
    equipment: "cable",
  },
  {
    id: "close-grip-cable-row",
    name: "Close Grip Cable Row",
    muscle: "back",
    category: "compound",
    equipment: "cable",
  },
  {
    id: "single-arm-cable-row",
    name: "Single Arm Cable Row",
    muscle: "back",
    category: "compound",
    equipment: "cable",
  },
  {
    id: "straight-arm-pulldown",
    name: "Straight Arm Pulldown",
    muscle: "back",
    category: "isolation",
    equipment: "cable",
  },
  {
    id: "rope-pulldown",
    name: "Rope Pulldown",
    muscle: "back",
    category: "isolation",
    equipment: "cable",
  },
  {
    id: "cable-pullover",
    name: "Cable Pullover",
    muscle: "back",
    category: "isolation",
    equipment: "cable",
  },
  {
    id: "wide-grip-lat-pulldown",
    name: "Wide Grip Lat Pulldown",
    muscle: "back",
    category: "compound",
    equipment: "cable",
  },
  {
    id: "close-grip-lat-pulldown",
    name: "Close Grip Lat Pulldown",
    muscle: "back",
    category: "compound",
    equipment: "cable",
  },
  {
    id: "reverse-grip-lat-pulldown",
    name: "Reverse Grip Lat Pulldown",
    muscle: "back",
    category: "compound",
    equipment: "cable",
  },
  {
    id: "single-arm-lat-pulldown",
    name: "Single Arm Lat Pulldown",
    muscle: "back",
    category: "compound",
    equipment: "cable",
  },
  {
    id: "neutral-grip-lat-pulldown",
    name: "Neutral Grip Lat Pulldown",
    muscle: "back",
    category: "compound",
    equipment: "cable",
  },
];