import { Exercise } from "./types";

export const bicepsExercises: Exercise[] = [
  {
    id: "barbell-curl",
    name: "Barbell Curl",
    muscle: "biceps",
    category: "compound",
    equipment: "barbell",
  },
  {
    id: "ez-bar-curl",
    name: "EZ Bar Curl",
    muscle: "biceps",
    category: "compound",
    equipment: "ez-bar",
  },
  {
    id: "standing-dumbbell-curl",
    name: "Standing Dumbbell Curl",
    muscle: "biceps",
    category: "compound",
    equipment: "dumbbell",
  },
  {
    id: "alternating-dumbbell-curl",
    name: "Alternating Dumbbell Curl",
    muscle: "biceps",
    category: "compound",
    equipment: "dumbbell",
  },
  {
    id: "incline-dumbbell-curl",
    name: "Incline Dumbbell Curl",
    muscle: "biceps",
    category: "isolation",
    equipment: "dumbbell",
  },
  {
    id: "seated-dumbbell-curl",
    name: "Seated Dumbbell Curl",
    muscle: "biceps",
    category: "isolation",
    equipment: "dumbbell",
  },
  {
    id: "hammer-curl",
    name: "Hammer Curl",
    muscle: "biceps",
    category: "compound",
    equipment: "dumbbell",
  },
  {
    id: "cross-body-hammer-curl",
    name: "Cross Body Hammer Curl",
    muscle: "biceps",
    category: "compound",
    equipment: "dumbbell",
  },
  {
    id: "preacher-barbell-curl",
    name: "Preacher Barbell Curl",
    muscle: "biceps",
    category: "isolation",
    equipment: "barbell",
  },
  {
    id: "preacher-ez-bar-curl",
    name: "Preacher EZ Bar Curl",
    muscle: "biceps",
    category: "isolation",
    equipment: "ez-bar",
  },
  {
    id: "preacher-dumbbell-curl",
    name: "Preacher Dumbbell Curl",
    muscle: "biceps",
    category: "isolation",
    equipment: "dumbbell",
  },
  {
    id: "machine-preacher-curl",
    name: "Machine Preacher Curl",
    muscle: "biceps",
    category: "isolation",
    equipment: "machine",
  },
  {
    id: "cable-curl",
    name: "Cable Curl",
    muscle: "biceps",
    category: "isolation",
    equipment: "cable",
  },
  {
    id: "rope-hammer-curl",
    name: "Rope Hammer Curl",
    muscle: "biceps",
    category: "isolation",
    equipment: "cable",
  },
  {
    id: "bayesian-cable-curl",
    name: "Bayesian Cable Curl",
    muscle: "biceps",
    category: "isolation",
    equipment: "cable",
  },
  {
    id: "high-cable-curl",
    name: "High Cable Curl",
    muscle: "biceps",
    category: "isolation",
    equipment: "cable",
  },
  {
    id: "reverse-ez-bar-curl",
    name: "Reverse EZ Bar Curl",
    muscle: "biceps",
    category: "compound",
    equipment: "ez-bar",
  },
  {
    id: "reverse-barbell-curl",
    name: "Reverse Barbell Curl",
    muscle: "biceps",
    category: "compound",
    equipment: "barbell",
  },
  {
    id: "zottman-curl",
    name: "Zottman Curl",
    muscle: "biceps",
    category: "compound",
    equipment: "dumbbell",
  },
  {
    id: "concentration-curl",
    name: "Concentration Curl",
    muscle: "biceps",
    category: "isolation",
    equipment: "dumbbell",
  },
  {
    id: "spider-curl",
    name: "Spider Curl",
    muscle: "biceps",
    category: "isolation",
    equipment: "ez-bar",
  },
  {
    id: "drag-curl",
    name: "Drag Curl",
    muscle: "biceps",
    category: "compound",
    equipment: "barbell",
  },
];