import { Exercise } from "./types";

export const chestExercises: Exercise[] = [
  {
    id: "flat-barbell-bench-press",
    name: "Flat Barbell Bench Press",
    muscle: "chest",
    category: "compound",
    equipment: "barbell",
  },
  {
    id: "incline-barbell-bench-press",
    name: "Incline Barbell Bench Press",
    muscle: "chest",
    category: "compound",
    equipment: "barbell",
  },
  {
    id: "decline-barbell-bench-press",
    name: "Decline Barbell Bench Press",
    muscle: "chest",
    category: "compound",
    equipment: "barbell",
  },
  {
    id: "smith-machine-bench-press",
    name: "Smith Machine Bench Press",
    muscle: "chest",
    category: "compound",
    equipment: "machine",
  },
  {
    id: "smith-machine-incline-press",
    name: "Smith Machine Incline Press",
    muscle: "chest",
    category: "compound",
    equipment: "machine",
  },
  {
    id: "smith-machine-decline-press",
    name: "Smith Machine Decline Press",
    muscle: "chest",
    category: "compound",
    equipment: "machine",
  },
  {
    id: "flat-dumbbell-press",
    name: "Flat Dumbbell Press",
    muscle: "chest",
    category: "compound",
    equipment: "dumbbell",
  },
  {
    id: "incline-dumbbell-press",
    name: "Incline Dumbbell Press",
    muscle: "chest",
    category: "compound",
    equipment: "dumbbell",
  },
  {
    id: "decline-dumbbell-press",
    name: "Decline Dumbbell Press",
    muscle: "chest",
    category: "compound",
    equipment: "dumbbell",
  },
  {
    id: "dumbbell-fly",
    name: "Dumbbell Fly",
    muscle: "chest",
    category: "isolation",
    equipment: "dumbbell",
  },
  {
    id: "incline-dumbbell-fly",
    name: "Incline Dumbbell Fly",
    muscle: "chest",
    category: "isolation",
    equipment: "dumbbell",
  },
  {
    id: "decline-dumbbell-fly",
    name: "Decline Dumbbell Fly",
    muscle: "chest",
    category: "isolation",
    equipment: "dumbbell",
  },
  {
    id: "dumbbell-pullover",
    name: "Dumbbell Pullover",
    muscle: "chest",
    category: "isolation",
    equipment: "dumbbell",
  },
  {
    id: "cable-crossover-high-to-low",
    name: "Cable Crossover (High to Low)",
    muscle: "chest",
    category: "isolation",
    equipment: "cable",
  },
  {
    id: "cable-crossover-low-to-high",
    name: "Cable Crossover (Low to High)",
    muscle: "chest",
    category: "isolation",
    equipment: "cable",
  },
  {
    id: "mid-cable-fly",
    name: "Mid Cable Fly",
    muscle: "chest",
    category: "isolation",
    equipment: "cable",
  },
  {
    id: "pec-deck-fly",
    name: "Pec Deck Fly",
    muscle: "chest",
    category: "isolation",
    equipment: "machine",
  },
  {
    id: "seated-chest-press-machine",
    name: "Seated Chest Press Machine",
    muscle: "chest",
    category: "compound",
    equipment: "machine",
  },
  {
    id: "incline-chest-press-machine",
    name: "Incline Chest Press Machine",
    muscle: "chest",
    category: "compound",
    equipment: "machine",
  },
  {
    id: "decline-chest-press-machine",
    name: "Decline Chest Press Machine",
    muscle: "chest",
    category: "compound",
    equipment: "machine",
  },
  {
    id: "standard-push-up",
    name: "Standard Push-Up",
    muscle: "chest",
    category: "compound",
    equipment: "bodyweight",
  },
  {
    id: "wide-grip-push-up",
    name: "Wide Grip Push-Up",
    muscle: "chest",
    category: "compound",
    equipment: "bodyweight",
  },
  {
    id: "diamond-push-up",
    name: "Diamond Push-Up",
    muscle: "chest",
    category: "compound",
    equipment: "bodyweight",
  },
];