import { Exercise } from "./types";

export const coreExercises: Exercise[] = [
  {
    id: "plank",
    name: "Plank",
    muscle: "core",
    category: "isolation",
    equipment: "bodyweight",
  },
  {
    id: "side-plank",
    name: "Side Plank",
    muscle: "core",
    category: "isolation",
    equipment: "bodyweight",
  },
  {
    id: "hollow-body-hold",
    name: "Hollow Body Hold",
    muscle: "core",
    category: "isolation",
    equipment: "bodyweight",
  },
  {
    id: "dead-bug",
    name: "Dead Bug",
    muscle: "core",
    category: "isolation",
    equipment: "bodyweight",
  },
  {
    id: "bird-dog",
    name: "Bird Dog",
    muscle: "core",
    category: "isolation",
    equipment: "bodyweight",
  },
  {
    id: "mountain-climber",
    name: "Mountain Climber",
    muscle: "core",
    category: "compound",
    equipment: "bodyweight",
  },
  {
    id: "hanging-leg-raise",
    name: "Hanging Leg Raise",
    muscle: "core",
    category: "isolation",
    equipment: "bodyweight",
  },
  {
    id: "captains-chair-leg-raise",
    name: "Captain's Chair Leg Raise",
    muscle: "core",
    category: "isolation",
    equipment: "bodyweight",
  },
  {
    id: "lying-leg-raise",
    name: "Lying Leg Raise",
    muscle: "core",
    category: "isolation",
    equipment: "bodyweight",
  },
  {
    id: "reverse-crunch",
    name: "Reverse Crunch",
    muscle: "core",
    category: "isolation",
    equipment: "bodyweight",
  },
  {
    id: "crunch",
    name: "Crunch",
    muscle: "core",
    category: "isolation",
    equipment: "bodyweight",
  },
  {
    id: "decline-crunch",
    name: "Decline Crunch",
    muscle: "core",
    category: "isolation",
    equipment: "bodyweight",
  },
  {
    id: "bicycle-crunch",
    name: "Bicycle Crunch",
    muscle: "core",
    category: "isolation",
    equipment: "bodyweight",
  },
  {
    id: "cable-crunch",
    name: "Cable Crunch",
    muscle: "core",
    category: "isolation",
    equipment: "cable",
  },
  {
    id: "rope-kneeling-crunch",
    name: "Rope Kneeling Crunch",
    muscle: "core",
    category: "isolation",
    equipment: "cable",
  },
  {
    id: "ab-wheel-rollout",
    name: "Ab Wheel Rollout",
    muscle: "core",
    category: "compound",
    equipment: "other",
  },
  {
    id: "stability-ball-rollout",
    name: "Stability Ball Rollout",
    muscle: "core",
    category: "compound",
    equipment: "other",
  },
  {
    id: "russian-twist",
    name: "Russian Twist",
    muscle: "core",
    category: "isolation",
    equipment: "other",
  },
  {
    id: "medicine-ball-twist",
    name: "Medicine Ball Twist",
    muscle: "core",
    category: "isolation",
    equipment: "other",
  },
  {
    id: "woodchopper",
    name: "Cable Woodchopper",
    muscle: "core",
    category: "compound",
    equipment: "cable",
  },
  {
    id: "pallof-press",
    name: "Pallof Press",
    muscle: "core",
    category: "isolation",
    equipment: "cable",
  },
  {
    id: "toe-touch",
    name: "Toe Touch",
    muscle: "core",
    category: "isolation",
    equipment: "bodyweight",
  },
  {
    id: "v-up",
    name: "V-Up",
    muscle: "core",
    category: "isolation",
    equipment: "bodyweight",
  },
  {
    id: "flutter-kick",
    name: "Flutter Kick",
    muscle: "core",
    category: "isolation",
    equipment: "bodyweight",
  },
];