import { Exercise } from "./types";

export const legsExercises: Exercise[] = [
  {
    id: "back-squat",
    name: "Back Squat",
    muscle: "legs",
    category: "compound",
    equipment: "barbell",
  },
  {
    id: "front-squat",
    name: "Front Squat",
    muscle: "legs",
    category: "compound",
    equipment: "barbell",
  },
  {
    id: "box-squat",
    name: "Box Squat",
    muscle: "legs",
    category: "compound",
    equipment: "barbell",
  },
  {
    id: "hack-squat",
    name: "Hack Squat",
    muscle: "legs",
    category: "compound",
    equipment: "machine",
  },
  {
    id: "smith-squat",
    name: "Smith Machine Squat",
    muscle: "legs",
    category: "compound",
    equipment: "machine",
  },
  {
    id: "leg-press",
    name: "Leg Press",
    muscle: "legs",
    category: "compound",
    equipment: "machine",
  },
  {
    id: "walking-lunge",
    name: "Walking Lunge",
    muscle: "legs",
    category: "compound",
    equipment: "dumbbell",
  },
  {
    id: "stationary-lunge",
    name: "Stationary Lunge",
    muscle: "legs",
    category: "compound",
    equipment: "dumbbell",
  },
  {
    id: "bulgarian-split-squat",
    name: "Bulgarian Split Squat",
    muscle: "legs",
    category: "compound",
    equipment: "dumbbell",
  },
  {
    id: "step-up",
    name: "Step Up",
    muscle: "legs",
    category: "compound",
    equipment: "dumbbell",
  },
  {
    id: "romanian-deadlift",
    name: "Romanian Deadlift",
    muscle: "legs",
    category: "compound",
    equipment: "barbell",
  },
  {
    id: "stiff-leg-deadlift",
    name: "Stiff Leg Deadlift",
    muscle: "legs",
    category: "compound",
    equipment: "barbell",
  },
  {
    id: "good-morning",
    name: "Good Morning",
    muscle: "legs",
    category: "compound",
    equipment: "barbell",
  },
  {
    id: "hip-thrust",
    name: "Barbell Hip Thrust",
    muscle: "legs",
    category: "compound",
    equipment: "barbell",
  },
  {
    id: "glute-bridge",
    name: "Glute Bridge",
    muscle: "legs",
    category: "compound",
    equipment: "bodyweight",
  },
  {
    id: "leg-extension",
    name: "Leg Extension",
    muscle: "legs",
    category: "isolation",
    equipment: "machine",
  },
  {
    id: "single-leg-extension",
    name: "Single Leg Extension",
    muscle: "legs",
    category: "isolation",
    equipment: "machine",
  },
  {
    id: "lying-leg-curl",
    name: "Lying Leg Curl",
    muscle: "legs",
    category: "isolation",
    equipment: "machine",
  },
  {
    id: "seated-leg-curl",
    name: "Seated Leg Curl",
    muscle: "legs",
    category: "isolation",
    equipment: "machine",
  },
  {
    id: "single-leg-curl",
    name: "Single Leg Curl",
    muscle: "legs",
    category: "isolation",
    equipment: "machine",
  },
  {
    id: "standing-calf-raise",
    name: "Standing Calf Raise",
    muscle: "legs",
    category: "isolation",
    equipment: "machine",
  },
  {
    id: "seated-calf-raise",
    name: "Seated Calf Raise",
    muscle: "legs",
    category: "isolation",
    equipment: "machine",
  },
  {
    id: "donkey-calf-raise",
    name: "Donkey Calf Raise",
    muscle: "legs",
    category: "isolation",
    equipment: "machine",
  },
  {
    id: "smith-calf-raise",
    name: "Smith Machine Calf Raise",
    muscle: "legs",
    category: "isolation",
    equipment: "machine",
  },
];