import { Exercise } from "./types";

export const shouldersExercises: Exercise[] = [
  {
    id: "barbell-overhead-press",
    name: "Barbell Overhead Press",
    muscle: "shoulders",
    category: "compound",
    equipment: "barbell",
  },
  {
    id: "seated-barbell-overhead-press",
    name: "Seated Barbell Overhead Press",
    muscle: "shoulders",
    category: "compound",
    equipment: "barbell",
  },
  {
    id: "behind-neck-press",
    name: "Behind Neck Press",
    muscle: "shoulders",
    category: "compound",
    equipment: "barbell",
  },
  {
    id: "arnold-press",
    name: "Arnold Press",
    muscle: "shoulders",
    category: "compound",
    equipment: "dumbbell",
  },
  {
    id: "seated-dumbbell-press",
    name: "Seated Dumbbell Shoulder Press",
    muscle: "shoulders",
    category: "compound",
    equipment: "dumbbell",
  },
  {
    id: "standing-dumbbell-press",
    name: "Standing Dumbbell Shoulder Press",
    muscle: "shoulders",
    category: "compound",
    equipment: "dumbbell",
  },
  {
    id: "machine-shoulder-press",
    name: "Machine Shoulder Press",
    muscle: "shoulders",
    category: "compound",
    equipment: "machine",
  },
  {
    id: "smith-shoulder-press",
    name: "Smith Machine Shoulder Press",
    muscle: "shoulders",
    category: "compound",
    equipment: "machine",
  },
  {
    id: "dumbbell-lateral-raise",
    name: "Dumbbell Lateral Raise",
    muscle: "shoulders",
    category: "isolation",
    equipment: "dumbbell",
  },
  {
    id: "seated-lateral-raise",
    name: "Seated Dumbbell Lateral Raise",
    muscle: "shoulders",
    category: "isolation",
    equipment: "dumbbell",
  },
  {
    id: "leaning-lateral-raise",
    name: "Leaning Dumbbell Lateral Raise",
    muscle: "shoulders",
    category: "isolation",
    equipment: "dumbbell",
  },
  {
    id: "single-arm-cable-lateral-raise",
    name: "Single Arm Cable Lateral Raise",
    muscle: "shoulders",
    category: "isolation",
    equipment: "cable",
  },
  {
    id: "dual-cable-lateral-raise",
    name: "Dual Cable Lateral Raise",
    muscle: "shoulders",
    category: "isolation",
    equipment: "cable",
  },
  {
    id: "cable-front-raise",
    name: "Cable Front Raise",
    muscle: "shoulders",
    category: "isolation",
    equipment: "cable",
  },
  {
    id: "dumbbell-front-raise",
    name: "Dumbbell Front Raise",
    muscle: "shoulders",
    category: "isolation",
    equipment: "dumbbell",
  },
  {
    id: "barbell-front-raise",
    name: "Barbell Front Raise",
    muscle: "shoulders",
    category: "isolation",
    equipment: "barbell",
  },
  {
    id: "plate-front-raise",
    name: "Plate Front Raise",
    muscle: "shoulders",
    category: "isolation",
    equipment: "other",
  },
  {
    id: "reverse-dumbbell-fly",
    name: "Reverse Dumbbell Fly",
    muscle: "shoulders",
    category: "isolation",
    equipment: "dumbbell",
  },
  {
    id: "reverse-pec-deck",
    name: "Reverse Pec Deck",
    muscle: "shoulders",
    category: "isolation",
    equipment: "machine",
  },
  {
    id: "face-pull",
    name: "Face Pull",
    muscle: "shoulders",
    category: "isolation",
    equipment: "cable",
  },
  {
    id: "cable-rear-delt-fly",
    name: "Cable Rear Delt Fly",
    muscle: "shoulders",
    category: "isolation",
    equipment: "cable",
  },
  {
    id: "upright-row-barbell",
    name: "Barbell Upright Row",
    muscle: "shoulders",
    category: "compound",
    equipment: "barbell",
  },
  {
    id: "upright-row-ez-bar",
    name: "EZ Bar Upright Row",
    muscle: "shoulders",
    category: "compound",
    equipment: "ez-bar",
  },
  {
    id: "upright-row-cable",
    name: "Cable Upright Row",
    muscle: "shoulders",
    category: "compound",
    equipment: "cable",
  },
  {
    id: "landmine-press",
    name: "Landmine Press",
    muscle: "shoulders",
    category: "compound",
    equipment: "landmine",
  },
];