import { Exercise } from "./types";

export const tricepsExercises: Exercise[] = [
  {
    id: "close-grip-bench-press",
    name: "Close Grip Bench Press",
    muscle: "triceps",
    category: "compound",
    equipment: "barbell",
  },
  {
    id: "jm-press",
    name: "JM Press",
    muscle: "triceps",
    category: "compound",
    equipment: "barbell",
  },
  {
    id: "barbell-skull-crusher",
    name: "Barbell Skull Crusher",
    muscle: "triceps",
    category: "isolation",
    equipment: "barbell",
  },
  {
    id: "ez-bar-skull-crusher",
    name: "EZ Bar Skull Crusher",
    muscle: "triceps",
    category: "isolation",
    equipment: "ez-bar",
  },
  {
    id: "lying-ez-bar-extension",
    name: "Lying EZ Bar Triceps Extension",
    muscle: "triceps",
    category: "isolation",
    equipment: "ez-bar",
  },
  {
    id: "seated-overhead-ez-extension",
    name: "Seated Overhead EZ Bar Extension",
    muscle: "triceps",
    category: "isolation",
    equipment: "ez-bar",
  },
  {
    id: "one-arm-dumbbell-extension",
    name: "One Arm Dumbbell Overhead Extension",
    muscle: "triceps",
    category: "isolation",
    equipment: "dumbbell",
  },
  {
    id: "two-arm-dumbbell-extension",
    name: "Two Arm Dumbbell Overhead Extension",
    muscle: "triceps",
    category: "isolation",
    equipment: "dumbbell",
  },
  {
    id: "seated-dumbbell-extension",
    name: "Seated Dumbbell Triceps Extension",
    muscle: "triceps",
    category: "isolation",
    equipment: "dumbbell",
  },
  {
    id: "rope-pushdown",
    name: "Rope Pushdown",
    muscle: "triceps",
    category: "isolation",
    equipment: "cable",
  },
  {
    id: "straight-bar-pushdown",
    name: "Straight Bar Pushdown",
    muscle: "triceps",
    category: "isolation",
    equipment: "cable",
  },
  {
    id: "v-bar-pushdown",
    name: "V-Bar Pushdown",
    muscle: "triceps",
    category: "isolation",
    equipment: "cable",
  },
  {
    id: "reverse-grip-pushdown",
    name: "Reverse Grip Pushdown",
    muscle: "triceps",
    category: "isolation",
    equipment: "cable",
  },
  {
    id: "single-arm-cable-pushdown",
    name: "Single Arm Cable Pushdown",
    muscle: "triceps",
    category: "isolation",
    equipment: "cable",
  },
  {
    id: "overhead-rope-extension",
    name: "Overhead Rope Extension",
    muscle: "triceps",
    category: "isolation",
    equipment: "cable",
  },
  {
    id: "single-arm-overhead-cable-extension",
    name: "Single Arm Overhead Cable Extension",
    muscle: "triceps",
    category: "isolation",
    equipment: "cable",
  },
  {
    id: "cross-body-cable-extension",
    name: "Cross Body Cable Extension",
    muscle: "triceps",
    category: "isolation",
    equipment: "cable",
  },
  {
    id: "machine-triceps-extension",
    name: "Machine Triceps Extension",
    muscle: "triceps",
    category: "isolation",
    equipment: "machine",
  },
  {
    id: "bench-dips",
    name: "Bench Dips",
    muscle: "triceps",
    category: "compound",
    equipment: "bodyweight",
  },
  {
    id: "parallel-bar-dips",
    name: "Parallel Bar Dips",
    muscle: "triceps",
    category: "compound",
    equipment: "bodyweight",
  },
];