export const quotes = [
  "Discipline beats motivation.",
  "Small progress is still progress.",
  "Consistency creates champions.",
  "Earn your results.",
  "One workout closer to your goal.",
  "Progress, not perfection.",
  "Train hard. Stay humble.",
  "Strong body. Strong mind.",
  "Push yourself every day.",
  "Great things take consistency.",
  "Success is built daily.",
  "Never skip the work.",
  "The grind never lies.",
  "Every rep counts.",
  "Stay patient. Stay consistent.",
  "Fitness is a lifestyle.",
  "You become what you repeat.",
  "Trust the process.",
  "Be stronger than yesterday.",
  "Keep showing up.",
  "The only bad workout is the one you didn't do.",
  "Champions train. Losers complain.",
  "Discipline creates freedom.",
  "Focus on progress.",
  "No excuses. Just results.",
  "Win today's battle.",
  "Be proud, but never satisfied.",
  "Action beats intention.",
  "Strength comes from consistency.",
  "Sweat today. Smile tomorrow.",
  "Hard work compounds.",
  "Success loves discipline.",
  "The body achieves what the mind believes.",
  "Make yourself proud.",
  "You are stronger than your excuses.",
  "Nothing changes if nothing changes.",
  "Dream big. Lift bigger.",
  "Pain is temporary. Pride is forever.",
  "One more set.",
  "Your future self will thank you.",
  "Every day is a fresh start.",
  "Be obsessed with improvement.",
  "Discomfort creates growth.",
  "Progress takes patience.",
  "Train for life.",
  "The mirror rewards consistency.",
  "Confidence is earned.",
  "Your habits define you.",
  "Lift with purpose.",
  "Stay hungry.",
  "Keep moving forward.",
  "Master the basics.",
  "Every workout matters.",
  "Health is your greatest wealth.",
  "The best project is you.",
  "Fall in love with the process.",
  "You vs You.",
  "Don't count days. Make days count.",
  "Today's effort shapes tomorrow.",
  "Never settle for average.",
  "The comeback starts today.",
  "Work until you're proud.",
  "Train. Recover. Repeat.",
  "Keep the promise you made to yourself.",
  "Nothing worth having comes easy.",
  "Winners never skip Mondays.",
  "Stay disciplined even when no one is watching.",
  "Excuses don't burn calories.",
  "Train with intent.",
  "Believe in your potential.",
  "Your limits are meant to be broken.",
  "Keep chasing better.",
  "One percent better every day.",
  "Discipline is self-respect.",
  "Be relentless.",
  "Fitness begins with one decision.",
  "Stay committed.",
  "Strive for excellence.",
  "Hard choices. Easy life.",
  "Be fearless in pursuit of your goals.",
  "Keep climbing.",
  "Train like a champion.",
  "Strong habits build strong bodies.",
  "Every step counts.",
  "You are capable of more.",
  "Keep earning your confidence.",
  "Focus. Lift. Repeat.",
  "Train beyond comfort.",
  "The work always shows.",
  "Your only competition is yesterday.",
  "Stay focused on your mission.",
  "Your body hears everything your mind says.",
  "Consistency wins every time.",
  "Don't stop until you're proud.",
  "Make discipline your superpower.",
  "Nothing can stop consistency.",
  "Stay resilient.",
  "Push beyond average.",
  "Create your own standard.",
  "Train with passion.",
  "Every champion was once a beginner.",
  "One more rep. One more victory.",
  "Be unstoppable.",
  "Success starts with showing up.",
  "Victory loves preparation.",
];

export function getDailyQuote() {
  const today = new Date();

  const dayNumber =
    today.getFullYear() * 1000 +
    today.getMonth() * 100 +
    today.getDate();

  return quotes[dayNumber % quotes.length];
}